# Generated by Django 3.2 on 2021-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Processed', models.CharField(max_length=240, verbose_name='Processed')),
                ('ODD', models.TextField(max_length=20, verbose_name='ODD')),
                ('GMDHMS', models.CharField(max_length=20, verbose_name='GMDHMS')),
                ('US', models.CharField(max_length=20, verbose_name='US')),
                ('FMIN', models.CharField(max_length=20, verbose_name='FMIN')),
                ('FMAX', models.CharField(max_length=20, verbose_name='FMAX')),
                ('DF', models.CharField(max_length=20, verbose_name='DF')),
                ('N', models.CharField(max_length=20, verbose_name='N')),
                ('SPECTER', models.CharField(max_length=20, verbose_name='SPECTER')),
                ('CRC', models.CharField(max_length=20, verbose_name='CRC')),
            ],
        ),
        migrations.CreateModel(
            name='CellAlarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Name')),
                ('Date', models.CharField(max_length=20, verbose_name='Date')),
                ('Floor', models.CharField(max_length=20, verbose_name='Floor')),
                ('cellID', models.CharField(max_length=20, verbose_name='cellID')),
                ('Status', models.CharField(max_length=20, verbose_name='Status')),
            ],
        ),
    ]
